"""
Dual Residual Network (DRN) - PyTorch implementation
Matches the architecture described in the paper excerpt:
ZeroPad(3) -> Conv7x7 s=2 -> BN -> ReLU -> MaxPool(3x3 s=2)
UniResidual blocks -> DualResidual (downsample & channel up) -> ...
AdaptiveAvgPool((4,4)) -> Flatten -> FC(512) -> FC(num_classes)

Author: generated by ChatGPT (adapted for training use)
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Optional


class UniResidualBlock(nn.Module):
    """Uni-Residual block: u_{n+1} = u_n + f(u_n, alpha3)
    Implemented as conv3x3 -> BN -> ReLU -> add skip
    preserves spatial dims and channels
    """
    def __init__(self, channels: int):
        super().__init__()
        self.conv = nn.Conv2d(channels, channels, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn = nn.BatchNorm2d(channels)
        self.relu = nn.ReLU(inplace=True)

    def forward(self, x):
        out = self.conv(x)
        out = self.bn(out)
        out = self.relu(out)
        return out + x


class DualResidualBlock(nn.Module):
    """Dual-Residual Block:
    - local path: 1x1 conv -> BN -> ReLU  (captures local mappings)
    - global path: 3x3 -> BN -> ReLU -> 3x3 -> BN -> ReLU (captures global mappings)
    combine paths by addition, then add residual (with projection if dims change).
    If stride != 1 or channel change, projection on residual is used.
    """
    def __init__(self, in_ch: int, out_ch: int, stride: int = 1):
        super().__init__()

        # local path (1x1)
        self.local = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel_size=1, stride=stride, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True)
        )

        # global path (two 3x3)
        self.global_path = nn.Sequential(
            nn.Conv2d(in_ch, out_ch, kernel_size=3, stride=stride, padding=1, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_ch, out_ch, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_ch),
            nn.ReLU(inplace=True),
        )

        # projection for residual if shape changes
        self.proj: Optional[nn.Module] = None
        if stride != 1 or in_ch != out_ch:
            self.proj = nn.Sequential(
                nn.Conv2d(in_ch, out_ch, kernel_size=1, stride=stride, bias=False),
                nn.BatchNorm2d(out_ch)
            )

        self.out_relu = nn.ReLU(inplace=True)

    def forward(self, x):
        a = self.local(x)
        b = self.global_path(x)
        out = a + b
        res = x if self.proj is None else self.proj(x)
        out = out + res
        out = self.out_relu(out)
        return out


class DRN(nn.Module):
    """Dual Residual Network (DRN) implementation.
    Default: in_ch=3, num_classes=2. Use in_ch=1 and num_classes=4 to match the paper example.
    """
    def __init__(self, in_ch: int = 3, num_classes: int = 2, dropout: float = 0.25):
        super().__init__()
        # Initial conv: 7x7 stride 2 -> 64 channels (we keep padding=3 to mimic ZeroPad2D(3,3))
        self.conv1 = nn.Conv2d(in_ch, 64, kernel_size=7, stride=2, padding=3, bias=False)
        self.bn1 = nn.BatchNorm2d(64)
        self.relu = nn.ReLU(inplace=True)
        # maxpool 3x3 stride2 with padding=1 to keep alignment like many ResNet variants
        self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)

        # Uni-Residual Blocks at 64 channels (keep dims)
        self.uni1 = nn.Sequential(
            UniResidualBlock(64),
            UniResidualBlock(64),
        )  # output: (64, H/4, W/4)

        # DualResidual: 64 -> 128, stride=2 (downsample)
        self.dual1 = nn.Sequential(
            DualResidualBlock(64, 128, stride=2),
        )  # output: (128, H/8, W/8)

        # Uni at 128
        self.uni2 = nn.Sequential(
            UniResidualBlock(128),
            UniResidualBlock(128),
        )

        # DualResidual: 128 -> 256, stride=2 (downsample)
        self.dual2 = nn.Sequential(
            DualResidualBlock(128, 256, stride=2),
        )  # output: (256, H/16, W/16)

        # Uni at 256
        self.uni3 = nn.Sequential(
            UniResidualBlock(256),
            UniResidualBlock(256),
        )

        # AdaptiveAvgPool to (4,4) as in paper, flatten => 256*4*4 = 4096
        self.avgpool = nn.AdaptiveAvgPool2d((4, 4))
        self.flatten_dim = 256 * 4 * 4

        # classifier
        self.fc1 = nn.Linear(self.flatten_dim, 512)
        self.dropout = nn.Dropout(p=dropout)
        self.fc_out = nn.Linear(512, num_classes)

        self._init_weights()

    def _init_weights(self):
        # Kaiming init for convs and linear; batchnorm weight=1 bias=0
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.kaiming_normal_(m.weight, nonlinearity='relu')
            elif isinstance(m, nn.Linear):
                nn.init.kaiming_normal_(m.weight, nonlinearity='relu')
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)

    def forward(self, x):
        # x: (B, in_ch, H, W)
        x = self.conv1(x)       # -> (B,64,H/2,W/2)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)     # -> (B,64,H/4,W/4)

        x = self.uni1(x)        # -> (B,64,H/4,W/4)
        x = self.dual1(x)       # -> (B,128,H/8,W/8)
        x = self.uni2(x)        # -> (B,128,H/8,W/8)
        x = self.dual2(x)       # -> (B,256,H/16,W/16)
        x = self.uni3(x)        # -> (B,256,H/16,W/16)

        x = self.avgpool(x)     # -> (B,256,4,4)
        x = torch.flatten(x, 1) # -> (B,4096)
        x = self.fc1(x)         # -> (B,512)
        x = F.relu(x)
        x = self.dropout(x)
        logits = self.fc_out(x) # -> (B,num_classes)
        return logits


def count_parameters(model: nn.Module) -> int:
    return sum(p.numel() for p in model.parameters() if p.requires_grad)


# -------------------------
# Minimal training utilities
# -------------------------
def build_optimizer(model: nn.Module, lr: float = 1e-3, weight_decay: float = 1e-4):
    return torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)


def train_step(model: nn.Module, batch, criterion, optimizer, device):
    """
    One training step on a single batch.
    batch: (inputs, targets)
    returns loss (scalar)
    """
    model.train()
    inputs, targets = batch
    inputs = inputs.to(device)
    targets = targets.to(device)

    optimizer.zero_grad()
    logits = model(inputs)
    loss = criterion(logits, targets)
    loss.backward()
    optimizer.step()
    return loss.item()


def validate_step(model: nn.Module, dataloader, criterion, device):
    model.eval()
    total_loss = 0.0
    total_correct = 0
    total = 0
    with torch.no_grad():
        for inputs, targets in dataloader:
            inputs = inputs.to(device)
            targets = targets.to(device)
            logits = model(inputs)
            loss = criterion(logits, targets)
            total_loss += loss.item() * inputs.size(0)
            preds = logits.argmax(dim=1)
            total_correct += (preds == targets).sum().item()
            total += inputs.size(0)
    avg_loss = total_loss / total
    acc = total_correct / total
    return avg_loss, acc


def save_model(model: nn.Module, path: str):
    torch.save(model.state_dict(), path)


def load_model(model: nn.Module, path: str, map_location=None):
    model.load_state_dict(torch.load(path, map_location=map_location))
    return model



